config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection { post :import }
  end
  resources :items
  resources :menus_items
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :menus_items, dependent: :destroy
  has_many :items, through: :menus_items
  accepts_nested_attributes_for :menus_items, allow_destroy: true
  validates_uniqueness_of :name, scope: :restaurant_id
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy!

    respond_to do |format|
      format.html { redirect_to menus_path, status: :see_other, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name, :restaurant_id, menus_items_attributes: [:id, :item_id, :price, :_destroy])
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.haml
= form_for @menu do |f|
  - if @menu.errors.any?
    #error_explanation
      %h2= "#{pluralize(@menu.errors.count, "error")} prohibited this menu from being saved:"
      %ul
        - @menu.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/menus/edit.html.haml
%h1 Editing menu

= render 'form'

= link_to 'Show', @menu
\|
= link_to 'Back', menus_path

app/views/menus/index.html.haml
%h1 Listing menus

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @menus.each do |menu|
      %tr
        %td= menu.name
        %td= link_to 'Show', menu
        %td= link_to 'Edit', edit_menu_path(menu)
        %td= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Menu', new_menu_path

app/views/menus/new.html.haml
%h1 New menu

= render 'form'

= link_to 'Back', menus_path

app/views/menus/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @menu.name

= link_to 'Edit', edit_menu_path(@menu)
\|
= link_to 'Back', menus_path