config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection { post :import }
  end
  resources :items
  resources :menus_items
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/menus_item.rb
class MenusItem < ApplicationRecord
  belongs_to :menu
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :menu_id, message: "already exists in this menu"
end

app/controllers/menus_items_controller.rb
class MenusItemsController < ApplicationController
  before_action :set_menus_item, only: %i[ show edit update destroy ]

  # GET /menus_items or /menus_items.json
  def index
    @menus_items = MenusItem.all
  end

  # GET /menus_items/1 or /menus_items/1.json
  def show
  end

  # GET /menus_items/new
  def new
    @menus_item = MenusItem.new
  end

  # GET /menus_items/1/edit
  def edit
  end

  # POST /menus_items or /menus_items.json
  def create
    @menus_item = MenusItem.new(menus_item_params)

    respond_to do |format|
      if @menus_item.save
        format.html { redirect_to @menus_item, notice: "Menus item was successfully created." }
        format.json { render :show, status: :created, location: @menus_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menus_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus_items/1 or /menus_items/1.json
  def update
    respond_to do |format|
      if @menus_item.update(menus_item_params)
        format.html { redirect_to @menus_item, notice: "Menus item was successfully updated." }
        format.json { render :show, status: :ok, location: @menus_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menus_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus_items/1 or /menus_items/1.json
  def destroy
    @menus_item.destroy!

    respond_to do |format|
      format.html { redirect_to menus_items_path, status: :see_other, notice: "Menus item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menus_item
      @menus_item = MenusItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menus_item_params
      params.require(:menus_item).permit(:item_id, :menu_id)
    end
end

app/helpers/menus_items_helper.rb
module MenusItemsHelper
end

app/views/menus_items/_form.html.haml
= form_for @menus_item do |f|
  - if @menus_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@menus_item.errors.count, "error")} prohibited this menus_item from being saved:"
      %ul
        - @menus_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :item
    = f.text_field :item
  .field
    = f.label :menu
    = f.text_field :menu
  .actions
    = f.submit 'Save'

app/views/menus_items/edit.html.haml
%h1 Editing menus_item

= render 'form'

= link_to 'Show', @menus_item
\|
= link_to 'Back', menus_items_path

app/views/menus_items/index.html.haml
%h1 Listing menus_items

%table
  %thead
    %tr
      %th Item
      %th Menu
      %th
      %th
      %th

  %tbody
    - @menus_items.each do |menus_item|
      %tr
        %td= menus_item.item
        %td= menus_item.menu
        %td= link_to 'Show', menus_item
        %td= link_to 'Edit', edit_menus_item_path(menus_item)
        %td= link_to 'Destroy', menus_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Menus item', new_menus_item_path

app/views/menus_items/new.html.haml
%h1 New menus_item

= render 'form'

= link_to 'Back', menus_items_path

app/views/menus_items/show.html.haml
%p#notice= notice

%p
  %b Item:
  = @menus_item.item
%p
  %b Menu:
  = @menus_item.menu

= link_to 'Edit', edit_menus_item_path(@menus_item)
\|
= link_to 'Back', menus_items_path