config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection { post :import }
  end
  resources :items
  resources :menus_items
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
  accepts_nested_attributes_for :menus, allow_destroy: true
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token, only: [:import]
  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy!

    respond_to do |format|
      format.html { redirect_to restaurants_path, status: :see_other, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    json_data = request.body.read
    service = RestaurantImportService.new(json_data)
    import_job  = service.call

    if import_job.completed?
      render json: {
        status: 'success',
        import_job_id: import_job.id,
        message: 'Import completed successfully',
        logs: import_job.import_logs.to_json
      }, status: :created
    else import_job.failed?
      render json: {
        status: 'error',
        import_job_id: import_job.id,
        message: 'Import failed',
        logs: import_job.import_logs.to_json
      }, status: :unprocessable_entity
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(
        :name,
        menus_attributes: [
        :id,
        :name,
        :_destroy,
        menus_items_attributes: [
          :id,
          :item_id,
          :price,
          :_destroy
        ]
      ])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  - if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
%h1 Listing restaurants

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @restaurants.each do |restaurant|
      %tr
        %td= restaurant.name
        %td= link_to 'Show', restaurant
        %td= link_to 'Edit', edit_restaurant_path(restaurant)
        %td= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @restaurant.name

= link_to 'Edit', edit_restaurant_path(@restaurant)
\|
= link_to 'Back', restaurants_path