config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection { post :import }
  end
  resources :items
  resources :menus_items
  resources :menus
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/item.rb
class Item < ApplicationRecord
  #NOTE: purposely leaves out dependent: :destroy to avoid cascading deletes
  #NOTE: database constraints will prevent deletion of items that are in use
  has_many :menus_items
  has_many :menus, through: :menus_items
  validates :name, presence: true, uniqueness: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, status: :see_other, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path